### ISSUE TITLE
Input doesn't work on headless wayland

### ISSUE THREAD

**Issue by dukzcry** [LizardByte/Sunshine#137]
### Describe the Bug

Sway run as
```
WLR_BACKENDS=headless WLR_LIBINPUT_NO_DEVICES=1 sway
```
Input (mouse, keyboard, virtual gamepad) doesn't work
If I run sway in non-headless mode, input works fine

### Expected Behavior

Input should work when sway is run in headless mode

### Sunshine Host Operating System and Version

Linux NixOS 21.11.333823.96b4157790f (Porcupine)

### Architecture

64 bit

### Sunshine Version

0.13.0

### GPU Type

AMD

### GPU Model

Vega 11

### GPU Driver/Mesa Version

mesa 21.2.5

**Comment by falk4243** [comment]
A little observation: I tested starting Steam via sway config and using Moonlight on iOS with a Xbox controller connected, input would be received in the sway session. The same goes for the Moonlight virtual controller. Using the on-screen or a Bluetooth keyboard results in their input being sent to the terminal / GUI (sway is running nested under X11) I have started the sway session from. 

If all input from the client device could be sent to the sway session, this could provide a nifty "poor man's" multi-seat setup where one machine can be used for working and gaming at the same time; apart from making use of Wayland's headless backend. I'll gladly provide further info / test if needed.

**Comment by falk4243** [comment]
Had a brief chat with the sway devs and it's clear now why the controller works: sway does not manage those at all and apps connect to them directly.

**Comment by jeremyvisser** [comment]
I can reproduce this issue as well (Fedora 36, Linux 5.17.13, AMD Radeon RX 6900XT, Sunshine 0.14.0, Sway 1.7, libinput 1.21), but I have an additional clue as to what might be happening.

While running Sway headless (and spawning Sunshine inside Sway), I had left GDM running on the primary head.

When I attached to Sunshine, I could see my Sway desktop, but my keyboard/mouse inputs were actually making it to the GDM session on the same host, but a different head (different Wayland session).

So inputs are being directed to the wrong place.

**Comment by qwert0p** [comment]
Having same issue (Arch Linux 5.18.3, AMD Radeon RX 590, latest sunshine git, Sway 1.8, libinput 1.21.0). After applying patch by sergioperez and running sway in headless mode input doesn't work, in wayvnc input works at the same time.

**Comment by jeremyvisser** [comment]
Just wanted to add some further thoughts on this. Disclaimer: I’m still fairly new to this area so I might be making bad assumptions (i.e. happy to be corrected).

Modern systems (based on systemd and logind) have the concept of a seat (`seat0` is default), with associated input devices and graphics outputs. For example, look at `loginctl seat-status seat0`.

When Sunshine fires up `uinput`, it’s logically similar to plugging in a second USB mouse: the input gets attached to the default seat (`seat0`). This is why the Sunshine input shows up on GDM, rather than your headless Sway.

Running headless Sway from a terminal as described above (`WLR_BACKENDS=headless WLR_LIBINPUT_NO_DEVICES=1 sway`) doesn't create an additional seat (`loginctl list-seats`). In fact, by setting `WLR_LIBINPUT_NO_DEVICES=1`, you're explicitly telling Sway **not** to use any existing inputs, even if you had hypothetically launched it as part of a seat and done a `loginctl attach seat-headless-sway /dev/uinput` (or similar).

While I don't know exactly what the solution should look like, I think a headless session should ideally run as a separate "seat" (as far as logind and libinput are concerned).

This likely implies using a display manager (e.g. GDM) to launch the session.

The burden for figuring this out falls to the Sway user community, not Sunshine. If a user session existed in a proper seat, with `uinput` attached appropriately, Sunshine would probably work correctly as-is.

**Comment by qwert0p** [comment]
Oh, i fixed my issue by simply setting  WLR_BACKENDS=headless,libinput and removing WLR_LIBINPUT_NO_DEVICES=1.

**Comment by falk4243** [comment]
@jeremyvisser I agree that this is nothing that can (or should)  be fixed on the Sunshine end of things, but find the discussion very interesting. My own "solution" was to setup sway accordng to their [Wiki](https://github.com/swaywm/sway/wiki) and start the headless session without a login manager via bash profile on another tty with the following startup options:

```
#!/bin/bash

export DESKTOP_SESSION="sway"
export XDG_CURRENT_DESKTOP="sway"
export XDG_SESSION_DESKTOP="sway"
export XDG_SESSION_TYPE="wayland"
export WLR_BACKENDS="headless,libinput"

exec dbus-run-session /usr/bin/sway -c /home/play/.config/sway/head
```
Input works as long as the session is focused and game controllers (not controlled via sway-input) *stay* focused on the sway session even after switching the focus back to another tty (X11 session). It's not a solution for everybody, but pretty much does what I'm asking for - using the main session while someone else can stream a game to the TV. 

As for the seatx configuration, are you sure that sway does not support this? the  [sway-input](https://manpages.debian.org/experimental/sway/sway-input.5.en.html) manual explicitly mentions assigning devices to seats, so *maybe* something could be done with that.

**Comment by falk4243** [comment]
> To address another question: why does `wayvnc` work properly? What does it do differently than Sunshine? Well, `wayvnc` creates virtual input devices specific to the current Wayland session, but rather than uinput, it uses the [virtual_keyboard_unstable_v1](https://github.com/swaywm/wlroots/blob/master/protocol/virtual-keyboard-unstable-v1.xml) protocol. GNOME explicitly [does not](https://gitlab.gnome.org/GNOME/mutter/-/issues/1974) support this protocol, and `wayvnc` is explicitly incompatible with GNOME or KDE. 

I've just had a quick chat with one of the sway devs and he suggested that implementing "wlr-virtual-{pointer,keyboard}" instead of going through evdev. I'm not a developer myself, but maybe the suggestion isn't completely outlandish and somebody working on Sunshine could pick this up sometime?

**Comment by rathmerdominik** [comment]
@falk4243 
This worked for a problem i had with Sunshine not accepting any kind of input.

Many thanks kind stranger!
Your solution helped me greatly!

**Comment by NickSica** [comment]
> @falk4243 This worked for a problem i had with Sunshine not accepting any kind of input.
> 
> Many thanks kind stranger! Your solution helped me greatly!

All you did was add those environment variables and run sway then sunshine? I still don't get any inputs and was wondering if there was more to the solution.

**Comment by wigust** [comment]
It was a challenge to make the cursor work in Android Moonlight client connecting to Sunshine running on a Guix system. Here is a quick guide how to do this.

On a first terminal:
```sudo seatd```

On a second terminal:
```
sudo chmod a+w /run/seatd.sock
sudo mkdir -p /run/user/1000
sudo chown oleg: /run/user/1000
export DESKTOP_SESSION="sway"
export XDG_CURRENT_DESKTOP="sway"
export XDG_SESSION_DESKTOP="sway"
export XDG_SESSION_TYPE="wayland"
export WLR_BACKENDS="headless,libinput"
sway
```

Inside Sway: Launch Sunshine and connect with Moonlight. You should see your cursor functioning properly and enjoy the Sway desktop experience!

**Comment by Kabouik** [comment]
> It was a challenge to make the cursor work in Android Moonlight client connecting to Sunshine running on a Guix system. Here is a quick guide how to do this.
> 
> On a first terminal: `sudo seatd`
> 
> On a second terminal:
> 
> ```
> sudo chmod a+w /run/seatd.sock
> sudo mkdir -p /run/user/1000
> sudo chown oleg: /run/user/1000
> export DESKTOP_SESSION="sway"
> export XDG_CURRENT_DESKTOP="sway"
> export XDG_SESSION_DESKTOP="sway"
> export XDG_SESSION_TYPE="wayland"
> export WLR_BACKENDS="headless,libinput"
> sway
> ```
> 
> Inside Sway: Launch Sunshine and connect with Moonlight. You should see your cursor functioning properly and enjoy the Sway desktop experience!

@wigust I would be very interested in knowing how you proceeded to run Sunshine on Guix, I can't see any package for it. Is it in aa private channel of yours?

**Comment by wigust** [comment]
> [@wigust](https://github.com/wigust) I would be very interested in knowing how you proceeded to run Sunshine on Guix, I can't see any package for it. Is it in aa private channel of yours?

That was a while ago. I used a package from Nix, which can be obtained via the nix-service-type service. However, I wouldn't recommend this approach—it's quite cumbersome to set up. Instead, creating a Guix package would be preferable. Nix builds graphical applications in a way that requires manual handling of /run/opengl-driver/lib, which adds unnecessary complexity. That said, this topic is beyond the scope of the current issue, so I don't think we should delve deeper into it here.

**Comment by Kabouik** [comment]
Thanks for your reply. I tried to make a package definition for it and was (very) slowly passing some road blocks, but then failed terribly when I realized the compilation needed `npm` with an Internet connection at some point (I guess for the web-UI part), which would have to be worked around for a Guix package. 

You're right, not going any more off-topic here. I'll try to remember pinging you if I ultimately open an issue here to work towards a native Guix package, if you don't mind.

**Comment by robtor-de** [comment]
In my setup (wayland + headless) it had something to do with the permissions of `/dev/uinput` which are set by an udev rule applied only on a normal user login session. I fixed it by adding a script that sets the permissions for my user properly:

```bash
#!/bin/bash

chown robtor:robtor /dev/uinput
```

**Comment by ReenigneArcher** [comment]
As of latest beta, you should only need to add your user to the input group now. And only in headless setups.

**Comment by Markus328** [comment]
My problem is that I'm running inside a container, and for somehow sway neither labwc can recognize the devices created **after** they have started. So I need to start sunshine before sway, labwc or restart the compositor after sunshine have started. Starting sunshine before compositor is possible but a bit tricky because I use wlr capure and the systemd-service needs the correct WAYLAND_DISPLAY to be set. 

Also, in a container, theres not a single input device before sunshine creates, so I must use `WLR_LIBINPUT_NO_DEVICES` that seems to be part of the trouble
