### ISSUE TITLE
Mouse pointer/cursor disappears

### ISSUE THREAD

**Issue by LeonEstrak** [LizardByte/Sunshine#1659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

The mouse pointer is permanently hidden in the system after a session. 

After using the moonlight client for a while, it hides the cursor when the game is run, and displays it only when used by the touchpad functionality. After the session ends, the mouse is still hidden from display in the PC and only reappears when used by the client touchpad.

### Expected Behavior

The mouse pointer should be visible after the session ends.

### Host Operating System

Windows

### Operating System Version

Windows 11 Pro 22621.2283

### Architecture

64 bit

### Sunshine commit or version

0.20.0

### Package

Windows - installer

### GPU Type

AMD

### GPU Model

RX 6800XT

### GPU Driver/Mesa Version

Driver Version 23.10.23.02-230720a-394204C-AMD-Software-Adrenalin-Edition

### Config

```Shell
Blank
```

### Relevant log output

```shell
[2023:09:20:17:12:25]: Info: Sunshine version: 0.20.0
[2023:09:20:17:12:25]: Info: Compiling shaders...
[2023:09:20:17:12:25]: Info: System tray created
[2023:09:20:17:12:25]: Info: Compiled shaders
[2023:09:20:17:12:25]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
---Not Relevant
[2023:09:20:17:12:27]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2023:09:20:17:12:27]: Info: 
[2023:09:20:17:12:27]: Info: Found encoder amdvce: [h264_amf, hevc_amf]
[2023:09:20:17:12:27]: Info: Configuration UI available at [https://localhost:47990]
[2023:09:20:17:12:27]: Info: Registered Sunshine mDNS service
```

**Comment by Nonary** [comment]
Please record the issue and upload a video demonstrating it.

**Comment by kirstus** [comment]
Seems like a windows issue. Happened to me only after using remote sessions multiple times, and not using the plugged-in mouse for hours. The mouse would still work normally, clicks and hover effects were triggered, and custom in-game cursors would appear, but the default windows cursor would only ever appear while i had a moonlight client connected.
Solved by unplugging my mouse and plugging it again. On laptops, disabling and re-enabling the touchpad should work too (FN + F6 or similar)

**Comment by clone1084** [comment]
This issue is still happening to me after long remote sessions. When I get back home and try to use the PC locally there is no mouse cursor visible (but it is working and highlighting things). It doesn't solve unplugging the mouse, I need to restart the PC to solve the issue.

**Comment by ArthurGerbelot** [comment]
Still have this issue.. and no it's not an time problem (even when I test a 10sec session the mouse is gone when end the session).
